version: "3.1"
services:
  mysqldb:
    image: mysql:latest
    container_name: mysql-phpmyadmin_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql-data/:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: mysql-phpmyadmin_phpmyadmin
    environment:
      - PMA_HOST=mysqldb